name: 'Git Tag Update'
run-name: 'PR Closure #${{ github.event.pull_request.number }}'

on:
  pull_request:
    types: [closed]
    branches:
    - main

permissions:
  id-token: write
  contents: write
  pull-requests: read

jobs:
  GetChangedElements:
    name: 'Get Changed Elements'
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && !startsWith(github.event.pull_request.head.ref, 'release/')
    outputs:
      elementsChanged: ${{ steps.elements-changed-output.outputs.elementsChanged }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Output elements to run CI for
      id: elements-changed-output
      uses: ./.github/actions/get-changed-elements
      with:
        changed-files-config: 'changed-files-config.json'
        

  PushNewTags:
    name: 'Push New Tag For ${{ matrix.element }}'
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && needs.GetChangedElements.outputs.elementsChanged
    needs: GetChangedElements
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        element: ${{fromJson(needs.GetChangedElements.outputs.elementsChanged)}}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 'Create head branch if deleted'
      shell: pwsh
      run: |
        echo "Local branches:"
        git branch --list
        echo "Remote branches:"
        git branch --list -r
        if ($null -eq (git branch --list ${{ github.event.pull_request.head.ref }})) {
          git branch ${{ github.event.pull_request.head.ref }}
        }
        else {
          git checkout ${{ github.event.pull_request.head.ref }}
        }
    - name: 'Install GitVersion'
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
        includePrerelease: 'false'
        preferLatestVersion: 'true'

    - name: GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: 'true'
        additionalArguments: '-b ${{ github.event.pull_request.head.ref }} /overrideconfig tag-prefix=${{ matrix.element }}-v'

    - name: Output to Job Summary
      id: output-element
      shell: pwsh
      run: |
        Write-Host "New Tag: ${{ matrix.element }}-v${{ steps.gitversion.outputs.majorMinorPatch }}"
        Write-Host "Element: ${{ matrix.element }}"
        Write-Host "New version: ${{ steps.gitversion.outputs.majorMinorPatch }}"
        "# :bookmark: New Tag: ${{ matrix.element }}-v${{ steps.gitversion.outputs.majorMinorPatch }} `r`n" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
        "## Element: ${{ matrix.element }} `r`n" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
        "## New Version: ${{ steps.gitversion.outputs.majorMinorPatch }} `r`n" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
        "## Branch: ${{ github.event.pull_request.head.ref }} `r`n" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append

    - name: Push New Git Tag
      shell: 'pwsh'
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git tag -f ${{ matrix.element }}-v${{ steps.gitversion.outputs.majorMinorPatch }}
        git push origin -f ${{ matrix.element }}-v${{ steps.gitversion.outputs.majorMinorPatch }}